version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090" # Prometheus UI
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml" # Prometheus configuration file
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000" # Grafana UI
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Set admin password for Grafana
    depends_on:
      - prometheus
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge



# actuator link -> http://192.168.0.113:8080/actuator/prometheus
# Prometheus link ->  http://localhost:9090
# Graphana link -> http://localhost:3000/