global:
  scrape_interval: 4s

scrape_configs:
  - job_name: 'spring-boot-application'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.0.113:8080'] # Update with your Spring Boot app's address and port
